services :
  turn :
    build : .
    container_name : turnny
    environment :
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://233.123.12.4:4317
      - TURNNY_TCP_PORTS=3478
      - TURNNY_UDP_PORTS=3478
      - RUST_LOG=INFO
    volumes :
      - ./turnserver.conf:/app/turnserver.conf
    ports :
      - "3478:3478/tcp"
      - "8443:8443/udp"
      - "3478:3478/udp"
