name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-publish:
    runs-on : ubuntu-latest
    permissions :
      contents : read
      packages : write

    steps :
      - name : Checkout Repo
        uses : actions/checkout@v4

      - name : GHCR Authentication
        uses : docker/login-action@v3
        with :
          registry : ghcr.io
          username : ${{ github.actor }}
          password : ${{ secrets.GITHUB_TOKEN }}

      - name : Push Docker Image
        uses : docker/build-push-action@v6.18.0
        with :
          context : .
          push : true
          tags : |
            gchr.io/${{ github.repository_owner }}/turnny:${{ github.sha }}
            gchr.io/${{ github.repository_owner }}/turnny:latest
